export const apiPath = {
  LOGIN: "/api/Users/signin",
  SIGNUP: "/api/Users/signup",
  ALL_PROJECT: "/api/Project/getAllProject",
  UPDATE_USER: "/api/Users/editUser",
  PROJECT_DETAIL: "/api/Project/getProjectDetail",
  UPDATE_PROJECT: "/api/Project/updateProject",
  DELETE_PROJECT: "/api/Project/deleteProject",
  CREATE_PROJECT: "/api/Project/createProjectAuthorize",
  CREATE_TASK: "/api/Project/createTask",
  TASK_DETAIL: "/api/Project/getTaskDetail",
  SEARCH_USER: "/api/Users/getUser",
  ASSIGN_USER: "/api/Project/assignUserProject",
  REMOVE_USER_FROM_PROJECT: "/api/Project/removeUserFromProject",
  REMOVE_USER_FROM_TASK: "/api/Project/removeUserFromTask",
  ASSIGN_USER_TASK: "/api/Project/assignUserTask",
  // USER_BY_PROJECT: "/api/Users/getUserByProjectId",
  ADD_COMMENT: "/api/Comment/insertComment",
  EDIT_COMMENT: "/api/Comment/updateComment",
  DELETE_COMMENT: "/api/Comment/deleteComment",
  DELETE_TASK: "/api/Project/removeTask",
  UPDATE_STATUS: "/api/Project/updateStatus",
  // UPDATE_ESTIMATE: "/api/Project/updateEstimate",
  // UPDATE_TIME_TRACKING: "/api/Project/updateTimeTracking",
};
